name: Setup the Release Dependencies
description: |
  This action sets up the release dependencies for the Python application.
  It installs the required dependencies and prepares the environment for the release process.
  The action is designed to be reusable and can be called from other workflows.
  It uses the `setup-python` action to set up the Python environment and install the required dependencies.
inputs:
  python-version:
    description: |
      Python version to use for the release process.
    required: false
    default: "3.13"
  prerelease:
    description: |
      Whether to create a pre-release version.
      This is useful for testing purposes.
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Dependency Manager 
      shell: bash
      run: |
        pip install --upgrade pip
        pip install --upgrade poetry
    
    - name: Install Dependencies
      working-directory: "./python"
      shell: bash
      run: |
        poetry install --with dev

    - name: Create Release
      working-directory: "./python"
      shell: bash
      run: |
        if [ "${{ inputs.prerelease }}" == "true" ]; then
          poetry run semantic-release version --vcs-release --changelog --as-prerelease
        else
          poetry run semantic-release version --vcs-release --changelog
        fi
