name: Build a Python Package
on:
  workflow_dispatch:
    inputs:
      python-version:
        description: "Python version to use"
        required: false
        type: choice
        options:
          - "3.13"
          - "3.12"
          - "3.11"
          - "3.10"
          - "3.9"
        default: "3.12"

jobs:
  build:
    name: Build the Python Package
    runs-on: ubuntu-latest
    timeout-minutes: 360
    permissions:
      contents: read
    steps:
      ## Set an Initial Step
      - name: Workshop Initial Step
        run: |
          echo "Hello World!"