name: Create a Release in GitHub
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed
    branches:
      - main

jobs:
  create-release:
    name: Create a Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    defaults:
      run:
        shell: bash
        working-directory: "./python"
    steps:
      # Checkout to be able to use the release action
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      # Use the setup-release action to create a release
      - name: Create Release
        id: create-release
        uses: ./.github/actions/setup-release
        with:
          python-version: ${{ github.event.inputs.python-version || '3.13' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_COMMIT_AUTHOR: "${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>"
